name: Build

on: [push, pull_request]

jobs:
  build:
    name: SDK build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'

      - run: yarn install

      - run: webpack
